version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
