root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

# Build command
[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
args_bin = []
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air_errors.log"
poll = false

[misc]
clean_on_exit = true

[watch]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
path_ignore = ["tmp"]

# Log settings
[log]
  time = true