volumes:
  postgres_data:

networks:
  default:
    name: grpc_network

services:
  db:
    image: postgres:16-alpine
    container_name: grpc-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: grpc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d grpc"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-app
    volumes:
      - .:/usr/src/app
    environment:
      # GIN_MODE: release
      AIR_ENV: dev
      DB_SOURCE: postgresql://root:password@db:5432/grpc?sslmode=disable
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
        restart: true
