volumes:
  postgres_data:

networks:
  default:
    name: grpc_network

services:
  db:
    image: postgres:16-alpine
    container_name: grpc-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: grpc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-app
    environment:
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      - db
