apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  # authenticate with IAM, this useful when you want to grant auth to a user who is not the creator of the cluster
  mapUsers: |
    - userarn: arn:aws:iam::037194225538:user/devder
      username: devder
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::037194225538:role/GitHubActionsRole
      username: github-actions
      groups:
        - system:masters
